[package]
name = "futures-cache"
version = "0.6.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/futures-cache"
homepage = "https://github.com/udoprog/futures-cache"
documentation = "https://docs.rs/futures-cache"
description = """
Futures-aware cache backed by sled.
"""

[dependencies]
futures-preview = {version = "0.3.0-alpha.17", features = ["async-await", "nightly"]}
serde = {version = "1.0.97", features = ["derive"]}
serde_json = "1.0.40"
serde_cbor = "0.10.1"
log = "0.4.7"
chrono = {version = "0.4.7", features = ["serde"]}
hex = "0.3.2"
parking_lot = "0.9.0"
hashbrown = "0.5.0"
pin-utils = "0.1.0-alpha.4"
crossbeam = "0.7.1"
sled = "0.24.1"

[dev-dependencies]
tempdir = "0.3.7"