[package]
name = "futures-cache"
version = "0.9.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/futures-cache"
homepage = "https://github.com/udoprog/futures-cache"
documentation = "https://docs.rs/futures-cache"
description = """
Futures-aware cache backed by sled.
"""

[dependencies]
futures-channel = "0.3.1"
serde = {version = "1.0.104", features = ["derive"]}
serde_json = "1.0.44"
serde_cbor = "0.10.2"
serde-hashkey = "0.2.1"
log = "0.4.7"
chrono = {version = "0.4.7", features = ["serde"]}
hex = "0.3.2"
parking_lot = "0.10.0"
hashbrown = "0.6.3"
pin-utils = "0.1.0-alpha.4"
crossbeam = "0.7.3"
sled = "0.30.3"

[dev-dependencies]
tempdir = "0.3.7"
futures = "0.3.1"